config/routes.rb
Pratamapolykem::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :carriers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "product/index"

  get "/dashboard" => "dashboard#index", as: :dashboard  
  get "/company_profile" => "company_profile#index", as: :profile  
  get "/gallery" => "gallery#index", as: :gallery  
  get "/tips_and_tricks" => "tip_trick#index", as: :tip_and_trick  
  get "/contact_us" => "contact_us#index", as: :contact_us  
  get "/product" => "product#index", as: :product
  post "/send_contact_form" => "contact_us#create", as: :send_contact_form  
  root :to => 'dashboard#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :photos
end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :basic_carrier, :expired_date, :requirement, :title
end

app/models/exelence.rb
class Exelence < ActiveRecord::Base
  attr_accessible :description, :title, :image
  mount_uploader :image, GalleryUploader
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	self.table_name = "galleries"
  attr_accessible :description, :image, :title, :album_id
  mount_uploader :image, GalleryUploader
  belongs_to :album
end

app/models/pratama_profile.rb
class PratamaProfile < ActiveRecord::Base
  attr_accessible :about, :address, :email, :logo, :name, :phone

  mount_uploader :image, ImageUploader
  
end

app/models/tip_trick.rb
class TipTrick < ActiveRecord::Base
  attr_accessible :author, :description, :image, :title

  mount_uploader :image, ImageUploader

  paginates_per 1
end

app/controllers/carriers_controller.rb
class CarriersController < InheritedResources::Base
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  
  def index; end

  def create
  	EmailNotifier.send_contact_form(params[:contact]).deliver
  	redirect_to contact_us_url, notice: "Thank you for contacting us"
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@tips_triks = TipTrick.order(:created_at)
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  	@albums = Album.all
  	@exelences = Exelence.all
  end

  def show_album
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end
end

app/controllers/tip_trick_controller.rb
class TipTrickController < ApplicationController
  def index
  	# @tips_triks = TipTrick.order(:created_at).page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/company_profile_helper.rb
module CompanyProfileHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper

  def cover_album(album)
  	album.photos.blank? ? "mosaic.jpg" : album.photos.sample.image.url
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/tip_trick_helper.rb
module TipTrickHelper
end

app/views/carriers/_form.html.slim
= form_for @carrier do |f|
  - if @carrier.errors.any?
    #error_explanation
      h2 = "#{pluralize(@carrier.errors.count, "error")} prohibited this carrier from being saved:"
      ul
        - @carrier.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :expired_date
    = f.date_select :expired_date
  .field
    = f.label :basic_carrier
    = f.text_area :basic_carrier
  .field
    = f.label :requirement
    = f.text_area :requirement
  .actions = f.submit 'Save'

app/views/carriers/edit.html.slim
h1 Editing carrier

== render 'form'

= link_to 'Show', @carrier
'|
= link_to 'Back', carriers_path

app/views/carriers/index.html.slim
h1 Listing carriers

table
  tr
    th Title
    th Expired date
    th Basic carrier
    th Requirement
    th
    th
    th

  - @carriers.each do |carrier|
    tr
      td = carrier.title
      td = carrier.expired_date
      td = carrier.basic_carrier
      td = carrier.requirement
      td = link_to 'Show', carrier
      td = link_to 'Edit', edit_carrier_path(carrier)
      td = link_to 'Destroy', carrier, :confirm => 'Are you sure?', :method => :delete

br

= link_to 'New Carrier', new_carrier_path

app/views/carriers/new.html.slim
h1 New carrier

== render 'form'

= link_to 'Back', carriers_path

app/views/carriers/show.html.slim
p#notice = notice

p
  strong Title:
  = @carrier.title
p
  strong Expired date:
  = @carrier.expired_date
p
  strong Basic carrier:
  = @carrier.basic_carrier
p
  strong Requirement:
  = @carrier.requirement

= link_to 'Edit', edit_carrier_path(@carrier)
'|
= link_to 'Back', carriers_path

app/views/photos/_modal_photo_gallery.html.slim
#modal-photo.modal.fade tabindex="-1" role="dialog" aria-labelledby="pratamaModalPhoto" aria-hidden="true"
  .modal-dialog
    .modal-content
      = image_tag "no_image.jpg", class: "width-100p"
      .modal-footer.bg-brand-color
        = link_to "close", "javascript:void(0);", "data-dismiss"=>"modal", class: "btn btn-default"

app/views/photos/index.html.slim
= content_for :stylesheet_contents do
  = stylesheet_link_tag "photo"
.container.marg-t-70
  .col-lg-12
    .panel.bg-title-brand-color.white.marg-b-5.title-container
      h3.no-marg Photos
      p.no-marg.arial album
    ul.list-inline.no-background.text-center
      li.list-inline-item.thumbnail.col-lg-3.marg-b-15
        = link_to image_tag("no_image.jpg", class: "col-lg-12 no-pad"), "#modal-photo", class: "col-lg-12 no-pad", "data-toggle"=>"modal"
        .caption.col-lg-12.no-pad
          h5.brand-color.text-left.no-marg Title
          p.font10.text-left.text-color.arial created at
      = render "modal_photo_gallery"
= content_for :javascript_contents do
  = javascript_include_tag "gallery"
javascript:
  $(document).ready(function(){
    $("#modal").onload(function(){
      $(".loader-photo").fadeIn();
    });
  });

app/views/tip_trick/_modal_view_tip_and_trick.html.slim
#modal-view-tip-and-trick.modal.fade tabindex="-1" role="dialog" aria-labelledby="pratamaModalPhoto" aria-hidden="true"
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title Title
        p.font10.text-left.text-color.arial created at
      .modal-body
        = image_tag "no_image.jpg", class: "width-100p marg-b-15"
        p.text-left.text-color.arial Lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum.
      .modal-footer.bg-brand-color
        = link_to "Close", "javascript:void(0);", "data-dismiss"=>"modal", class: "btn btn-default btn-sm"

app/views/tip_trick/index.html.slim
.container.marg-t-70
  .col-lg-12
    .panel.bg-title-brand-color.white.marg-b-5.title-container
      h3.no-marg Tips and Tricks
    ul.list-group
      li.list-group-item.media
        .col-lg-5.col-lg-push-7
          = link_to image_tag("no_image.jpg", class: "media-object pull-left width-100p marg-b-15"), "#modal-view-tip-and-trick", "data-toggle"=>"modal", class: "text-center width-100p", "data-toggle"=>"modal"
        .caption.media-body.col-lg-7.col-lg-push-5
          h4.brand-color.text-left.no-marg.media-header Title
          p.font10.text-left.text-color.arial created at
          p.text-left.text-color.arial Lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum lorem ipsum dipsum.
          p.font12.text-left= link_to "view more", "#modal-view-tip-and-trick", "data-toggle"=>"modal"
        = render "modal_view_tip_and_trick"
= content_for :javascript_contents do
  = javascript_include_tag "tip_trick"