config/routes.rb
Pratamapolykem::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :carriers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "product/index"

  get "/dashboard" => "dashboard#index", as: :dashboard  
  get "/company_profile" => "company_profile#index", as: :profile  
  get "/gallery" => "gallery#index", as: :gallery  
  get "/tips_and_tricks" => "tip_trick#index", as: :tip_and_trick  
  get "/contact_us" => "contact_us#index", as: :contact_us  
  get "/product" => "product#index", as: :product
  post "/send_contact_form" => "contact_us#create", as: :send_contact_form  
  root :to => 'dashboard#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :photos
end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :basic_carrier, :expired_date, :requirement, :title
end

app/models/exelence.rb
class Exelence < ActiveRecord::Base
  attr_accessible :description, :title, :image
  mount_uploader :image, GalleryUploader
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	self.table_name = "galleries"
  attr_accessible :description, :image, :title, :album_id
  mount_uploader :image, GalleryUploader
  belongs_to :album
end

app/models/pratama_profile.rb
class PratamaProfile < ActiveRecord::Base
  attr_accessible :about, :address, :email, :logo, :name, :phone

  mount_uploader :image, ImageUploader
  
end

app/models/tip_trick.rb
class TipTrick < ActiveRecord::Base
  attr_accessible :author, :description, :image, :title

  mount_uploader :image, ImageUploader

  paginates_per 1
end

app/controllers/carriers_controller.rb
class CarriersController < InheritedResources::Base
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  
  def index; end

  def create
  	EmailNotifier.send_contact_form(params[:contact]).deliver
  	redirect_to contact_us_url, notice: "Thank you for contacting us"
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@tips_triks = TipTrick.order(:created_at)
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  	@albums = Album.all
  	@exelences = Exelence.all
  end

  def show_album
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/company_profile_helper.rb
module CompanyProfileHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper

  def cover_album(album)
  	album.photos.blank? ? "mosaic.jpg" : album.photos.sample.image.url
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/tip_trick_helper.rb
module TipTrickHelper
end

app/views/contact_us/index.html.slim
.container.marg-t-70
  .width-50p.marg-c
    .panel.bg-title-brand-color.white.marg-b-5.title-container
      h3.no-marg Contact us
    .well.col-lg-12
      - if notice
        .alert= notice
      = form_tag send_contact_form_path, class: "form-horizontal", role: "form" do
        .form-group
          label.col-lg-2.control-label.font12.arial for="inputFirstName" First Name
          .col-lg-10
            = text_field_tag 'contact[first_name]', nil, placeholder: 'First Name', id: "inputFirstName", class: "form-control"
        .form-group
          label.col-lg-2.control-label.font12.arial for="inputLastName" Last Name
          .col-lg-10
            = text_field_tag 'contact[last_name]', nil, placeholder: 'Last Name', id: "inputLastName", class: "form-control"
        .form-group
          label.col-lg-2.control-label.font12.arial for="inputEmail" Email
          .col-lg-10
            = email_field_tag 'contact[email]', nil, placeholder: 'Email', id: "inputEmail", class: "form-control"
        .form-group
          label.col-lg-2.control-label.font12.arial for="inputEmail" Message
          .col-lg-10
            = text_area_tag "contact[message]", nil, id: "inputMessage", class: "form-control", style:"resize: none;"
        .form-group
          .col-lg-2.col-lg-push-10
          .col-lg-10.col-lg-push-2.text-right
            button.btn.btn-default type="submit" Send
= content_for :javascript_contents do
  = javascript_include_tag "contact_us"