config/routes.rb
Pratamapolykem::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :carriers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "product/index"

  get "/dashboard" => "dashboard#index", as: :dashboard  
  get "/company_profile" => "company_profile#index", as: :profile  
  get "/gallery" => "gallery#index", as: :gallery  
  get "/tips_and_tricks" => "tip_trick#index", as: :tip_and_trick  
  get "/contact_us" => "contact_us#index", as: :contact_us  
  get "/product" => "product#index", as: :product
  post "/send_contact_form" => "contact_us#create", as: :send_contact_form  
  root :to => 'dashboard#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :photos
end

app/models/carrier.rb
class Carrier < ActiveRecord::Base
  attr_accessible :basic_carrier, :expired_date, :requirement, :title
end

app/models/exelence.rb
class Exelence < ActiveRecord::Base
  attr_accessible :description, :title, :image
  mount_uploader :image, GalleryUploader
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	self.table_name = "galleries"
  attr_accessible :description, :image, :title, :album_id
  mount_uploader :image, GalleryUploader
  belongs_to :album
end

app/models/pratama_profile.rb
class PratamaProfile < ActiveRecord::Base
  attr_accessible :about, :address, :email, :logo, :name, :phone

  mount_uploader :image, ImageUploader
  
end

app/models/tip_trick.rb
class TipTrick < ActiveRecord::Base
  attr_accessible :author, :description, :image, :title

  mount_uploader :image, ImageUploader

  paginates_per 1
end

app/controllers/carriers_controller.rb
class CarriersController < InheritedResources::Base
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  	@albums = Album.all
  	@exelences = Exelence.all
  end

  def show_album
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carriers_helper.rb
module CarriersHelper
end

app/helpers/company_profile_helper.rb
module CompanyProfileHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper

  def cover_album(album)
  	album.photos.blank? ? "mosaic.jpg" : album.photos.sample.image.url
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/tip_trick_helper.rb
module TipTrickHelper
end

app/views/email_notifier/send_contact_form.html.erb
<p>Hi, my name <%= @data[:first_name] + "" + @data[:last_name]  %></p>
<br />
<p><%= @data[:message] %></p>

app/views/layouts/application.html.slim
DOCTYPE  html
html
	head
	  title Pratamapolykem
	  meta content="67b4cf6060cb0e01-573f462cc134cfd9-g8e85acc3927937c8-13" name="google-translate-customization"
	  = stylesheet_link_tag    "application", :media => "all"
	  = yield :stylesheet_contents
	  = javascript_include_tag "application"
	  = yield :javascript_contents
	  = csrf_meta_tags
	body
		.navbar.navbar-fixed-top.header-container
			.container
				button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
					span.icon-bar
					span.icon-bar
					span.icon-bar
				.logo.armata
					/ - if !@profile.nil?
					/ 	= link_to dashboard_path, class: "navbar-brand" do
					/ 		= image_tag "/assets/pratama_logo.png", class: "width-32 marg-r-10"
					/ 		= @profile.name.titleize
					/ - else
					/ 	= link_to dashboard_path, class: "navbar-brand" do
					/ 		= image_tag "/assets/pratama_logo.png", class: "width-32 marg-r-10"
					/ 		= "Corporate Name"
				.nav.navbar-nav.nav-collapse.collapse.navbar-responsive-collapse.nav-collapse-scrollable.width-100p
					ul.nav.navbar-nav.width-100p
						li.home
							= link_to "Home", dashboard_path, class: "home"
						li.profile
							= link_to "Company Profile", profile_path, class: "profile"
						li.product
							= link_to "javasript:void(0);", class: "product dropdown-toggle", "data-toggle"=>"dropdown" do
								| Products
								span.caret
							ul.dropdown-menu
								li
									= link_to "All Products", "javascript:void(0);"
								li
									= link_to "Distributors and Agents", "javascript:void(0);"
								li
									= link_to "Characteristics", "javascript:void(0);"
								li
									= link_to "Installation", "javascript:void(0);"
						li.gallery
							= link_to "Gallery", gallery_path, class: "gallery"
						li.trick
							= link_to "Tips and Tricks", tip_and_trick_path, class: "trick"
						li.contact
							= link_to "Contact Us", contact_us_path, class: "contact"
						li.testimonial
							= link_to "Testimony", "javascript:void(0);", class: "testimonial"
						li.translation-links.pull-right
							.translation-icons style="visibility:hidden"
							  = link_to "javascript:void(0);", "data-placement"=>"0" do
							  	= image_tag "england.png", "data-toggle"=>"tooltip", "data-placement"=>"bottom", class: "information", "data-original-title"=>"english language"
							  = link_to "javascript:void(0);", "data-placement"=>"1" do
							  	= image_tag "ind.png", "data-toggle"=>"tooltip", "data-placement"=>"bottom", class: "information", "data-original-title"=>"indonesian language"
							#google_translate_element style="display:none"
		= yield
		.col-lg-12
			#footer.container-fluid.text-center
				.container
					- unless controller_name.eql? "company_profile"
						.col-lg-12.text-center
							ul.list-inline.information-container
								li.list-inline-item.information data-toggle="tooltip" data-placement="top" data-original-title="Address"
									= image_tag "home.svg", class: "width-20 item-information"
									= "Address"
								li.list-inline-item.information data-toggle="tooltip" data-placement="top" data-original-title="Location"
									= image_tag "pin.svg", class: "width-20 item-information"
									= "Location"
								li.list-inline-item.information data-toggle="tooltip" data-placement="top" data-original-title="Messenger"
									= image_tag "at.svg", class: "width-20 item-information"
									= "Messenger"
								li.list-inline-item.information data-toggle="tooltip" data-placement="top" data-original-title="Phone"
									= image_tag "iphone.svg", class: "width-20 item-information"
									= "Phone"
								li.list-inline-item.information data-toggle="tooltip" data-placement="top" data-original-title="Email"
									= image_tag "mail.svg", class: "width-20 item-information"
									= "Email"
					ul.list-inline
						li.list-inline-item.home
							= link_to "Dashboard", dashboard_path
						li.list-inline-item.profile
							= link_to "Company Profile", profile_path, class: "profile"
						li.list-inline-item.product
							= link_to "Products", product_path
						li.list-inline-item.gallery
							= link_to "Gallery", gallery_path
						li.list-inline-item.trick
							= link_to "Tips and Tricks", tip_and_trick_path
						li.list-inline-item.contact
							= link_to "Contact Us", contact_us_path
						li.list-inline-item
							= link_to "Specification", "javascript:void(0);"
						li.list-inline-item
							= link_to "Distributors and Agents", "javascript:void(0);"
						li.list-inline-item
							= link_to "Characteristics", "javascript:void(0);"
						li.list-inline-item
							= link_to "Installation", "javascript:void(0);"
						li.list-inline-item
							= link_to "Testimonials", "javascript:void(0);"
					.col-lg-12.copyright.text-center.marg-v-15
						p.label.label-default copyright &copy; Pratama Polykem 2013
		javascript:
		   	function googleTranslateElementInit() {
		    	new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'en,id', layout: google.translate.TranslateElement.InlineLayout.SIMPLE, autoDisplay: false}, 'google_translate_element');
		  	}

		  	$(window).load(function () {

    			$('.translation-icons').css('visibility', 'visible');
        	$('.translation-icons a').click(function(e) {
            e.preventDefault();
            var placement = $(this).data('placement');
            var lang_num = $('.translation-icons a').length;
            var $frame = $('.goog-te-menu-frame:first');

            if (!$frame.size()) {
                alert("Error: Could not find Google translate frame.");
                return false;
            }

            var langs = $('.goog-te-menu-frame:first').contents().find('a span.text');

            if(langs.length != lang_num) placement = placement+1;
            $(".skiptranslate").hide();

            langs.eq(placement).click();
            return false;
        	});
				});

		script src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit" type="text/javascript"